# Generated by Django 6.0.3 on 2026-04-01 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0002_bankaccount_is_frozen'),
        ('transactions', '0002_transaction_flag_reason_transaction_is_flagged_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('FREEZE_ACCOUNT', 'Freeze Account'), ('UNFREEZE_ACCOUNT', 'Unfreeze Account'), ('ROLE_CHANGE', 'Role Change'), ('APPROVE_TRANSFER', 'Approve Transfer'), ('REJECT_TRANSFER', 'Reject Transfer'), ('UPDATE_SETTINGS', 'Update Global Settings'), ('MANAGE_OTP', 'Manage OTP Access')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.bankaccount')),
                ('target_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targeted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=500.0, max_digits=12)),
                ('max_transfer_limit', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12)),
                ('daily_withdrawal_limit', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
