# Generated by Django 6.0.3 on 2026-04-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
